// <auto-generated />
using System;
using CarPricePrediction.Module.BusinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarPricePrediction.Module.Migrations
{
    [DbContext(typeof(CarPricePredictionEFCoreDbContext))]
    partial class CarPricePredictionEFCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Proxies:ChangeTracking", true)
                .HasAnnotation("Proxies:CheckEquality", true)
                .HasAnnotation("Proxies:LazyLoading", false)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarPricePrediction.Module.BusinessObjects.VwCars", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("engineSize")
                        .HasColumnType("float");

                    b.Property<string>("fuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("mileage")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("mpg")
                        .HasColumnType("float");

                    b.Property<int?>("price")
                        .HasColumnType("int");

                    b.Property<int?>("tax")
                        .HasColumnType("int");

                    b.Property<string>("transmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("VwCars", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
